#ifndef ERROR_CODE_H
#define ERROR_CODE_H

namespace filerepo
{

enum
{
    SUCCEED = 0,
    HASH_FILE_FAILED,
    CREATE_DIRECTORY_FAILED,
    COMMIT_FILE_FAILED,
    UNIMPLEMENT,
    FILE_NOT_OPENED,
    FILE_NOT_FOUND,
    OPEN_FILE_FAILED,
    READ_FILE_FAILED,
    WRITE_FILE_FAILED,
    OPEN_WRITE_STREAM_FAILED,
    OPEN_READ_STREAM_FAILED,
    FILE_REPO_NOT_OPENED,
    ADD_FILE_ENTRY_FAILED,
    REMOVE_FILE_ENTRY_FAILED,
    REPO_VERSION_INCOMPATIBLE,
    REPO_VERSION_NOT_EXIST,
    SAVE_INDEX_FAILED,
    COPY_INDEX_FAILED,
    CREATE_TAG_FAILED,
    BACKUP_TAGS_EMPTY,
    BACKUP_TAG_NOT_EXIST,
    FILE_PATH_EMPTY,
};

#define CHECK_SUCCEED(ret) \
    if (SUCCEED == ret) return true; else return false;
#define IS_SUCCEED(ret) (SUCCEED == ret)

}
#endif